version: '3.8'

services:
  limos-api:
    build: .
    container_name: limos-api
    ports:
      - "8000:8000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    volumes:
      - ./storage:/app/storage
      - ./projects:/app/projects
      - ./core:/app/core
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Uncomment when ready to add database
  # postgres:
  #   image: postgres:16-alpine
  #   container_name: limos-db
  #   environment:
  #     - POSTGRES_DB=limos
  #     - POSTGRES_USER=limos
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  # redis:
  #   image: redis:7-alpine
  #   container_name: limos-cache
  #   ports:
  #     - "6379:6379"

# volumes:
#   postgres_data: