environment: development
debug: true
log_level: DEBUG

api:
  host: 0.0.0.0
  port: 8000
  reload: true
  workers: 1

agent:
  max_turns: 10
  permission_mode: acceptEdits
  timeout: 300

storage:
  base_path: storage
  receipts: storage/processed_data/receipts