environment: production
debug: false
log_level: WARNING

api:
  host: 0.0.0.0
  port: 8000
  reload: false
  workers: 4

agent:
  max_turns: 20
  permission_mode: ask
  timeout: 600

storage:
  base_path: /data/storage
  receipts: /data/storage/processed_data/receipts

security:
  require_api_key: true
  rate_limit: 100